application: map-of-life
version: change
runtime: python27
threadsafe: true
api_version: 1

inbound_services:
- warmup

builtins:
- remote_api: on

handlers:

- url: /js
  static_dir: js
  
- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /cache/.*
  script: cache_handler.application
  
- url: /api/change
  script: change_handler.application
      
- url: /api/year
  script: year_handler.application
  
- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))
 
- url: /
  script: app.application

- url: /.*
  script: app.application

libraries:
- name: pycrypto
  version: "2.3"


